#Experiment 15

##Data Normalization and Data Type Conversion
##Part-A Data Normalization

###Soumya Khanna - 25070123111

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,4500],
    'Units_Sold':[25,60,35,80,50,15],
    'Discount': [10,15,12,20,18,8]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera   4500          15         8

In [ ]:
#Price Normalization
min_price = df['Price'].min()
max_price = df['Price'].max()

df['Price_Normalized'] = (df['Price'] - min_price) / (max_price - min_price)

print(df[['Product', 'Price', 'Price_Normalized']])

      Product  Price  Price_Normalized
0      Laptop  55000          1.000000
1      Mobile  20000          0.339623
2      Tablet  30000          0.528302
3  Headphones   2000          0.000000
4  Smartwatch   8000          0.113208
5      Camera   4500          0.047170

In [ ]:
#Normalization of Multiple Columns
cols = ['Price', 'Units_Sold', 'Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df_norm

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.047170    0.000000  0.000000

In [ ]:
#Z-Score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
df

      Product  Price  Units_Sold  Discount  Price_Normalized  Units_Zscore
0      Laptop  55000          25        10          1.000000     -0.799885
1      Mobile  20000          60        15          0.339623      0.660775
2      Tablet  30000          35        12          0.528302     -0.382554
3  Headphones   2000          80        20          0.000000      1.495437
4  Smartwatch   8000          50        18          0.113208      0.243443
5      Camera   4500          15         8          0.047170     -1.217216

In [ ]:
#Decimal Scaling
df['Price_Scaled'] = df['Price'] / 10000

print(df[['Product','Price', 'Price_Scaled' ]])

      Product  Price  Price_Scaled
0      Laptop  55000          5.50
1      Mobile  20000          2.00
2      Tablet  30000          3.00
3  Headphones   2000          0.20
4  Smartwatch   8000          0.80
5      Camera   4500          0.45

##Part-B Data Encoding

In [ ]:
import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df1 = pd.DataFrame(data)
df1

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value
0,101,Male,UPI,Electronics,Pune,4500
1,102,Female,Credit Card,Clothing,Mumbai,2300
2,103,Female,Debit Card,Home,Delhi,3200
3,104,Male,COD,Electronics,Bangalore,5200
4,105,Female,UPI,Beauty,Pune,1800
5,106,Male,Debit Card,Electronics,Hyderabad,4100

In [ ]:
#Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['Gender_Label'] = le.fit_transform(df1['Customer_Gender'])
df1

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label
0,101,Male,UPI,Electronics,Pune,4500,1
1,102,Female,Credit Card,Clothing,Mumbai,2300,0
2,103,Female,Debit Card,Home,Delhi,3200,0
3,104,Male,COD,Electronics,Bangalore,5200,1
4,105,Female,UPI,Beauty,Pune,1800,0
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1

In [ ]:
df1['City_Label'] = le.fit_transform(df1['City'])
df1

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3
2,103,Female,Debit Card,Home,Delhi,3200,0,1
3,104,Male,COD,Electronics,Bangalore,5200,1,0
4,105,Female,UPI,Beauty,Pune,1800,0,4
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2

In [ ]:
#Method 2: One-Hot Encoding
df_encoded = pd.get_dummies(df1, columns=['Customer_Gender'])
df_encoded

,Order_ID,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label,Customer_Gender_Female,Customer_Gender_Male
0,101,UPI,Electronics,Pune,4500,1,4,False,True
1,102,Credit Card,Clothing,Mumbai,2300,0,3,True,False
2,103,Debit Card,Home,Delhi,3200,0,1,True,False
3,104,COD,Electronics,Bangalore,5200,1,0,False,True
4,105,UPI,Beauty,Pune,1800,0,4,True,False
5,106,Debit Card,Electronics,Hyderabad,4100,1,2,False,True

In [ ]:
df_dummies = pd.get_dummies(df1, columns=['Payment_Method'], drop_first=True)
df_dummies

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,City_Label,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,4,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,3,True,False,False
2,103,Female,Home,Delhi,3200,0,1,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,0,False,False,False
4,105,Female,Beauty,Pune,1800,0,4,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,2,False,True,False

#Amazon Data Set Tasks

In [ ]:
import pandas as pd
d = pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")
d

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
#Min max normalization for price
min_price = d['Price'].min()
max_price = d['Price'].max()
d['Price_Normalized'] = (df['Price'] - min_price) / (max_price - min_price)
d

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_Normalized
0,P101,Wireless Mouse,799,4.3,1520,350,2.214615
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.797611
2,P103,USB Keyboard,699,4.1,870,180,1.202470
3,P104,Gaming Headset,2499,4.6,2100,410,0.068866
4,P105,Smartwatch,3999,4.4,3050,520,0.311781
5,P106,Power Bank,1199,4.2,1750,390,0.170081
6,P107,Laptop Stand,899,4.0,620,140,NaN
7,P108,Webcam,1899,4.3,1120,260,NaN
8,P109,Portable SSD,5499,4.7,1850,330,NaN
9,P110,Wireless Charger,999,4.2,760,190,NaN
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,NaN
11,P112,Mechanical Keyboard,4599,4.5,2100,290,NaN
12,P113,Gaming Mouse,1599,4.4,1300,340,NaN
13,P114,Tablet Stand,699,4.1,540,120,NaN
14,P115,USB Hub,899,4.2,870,200,NaN
15,P116,External Hard Drive,6499,4.6,2300,310,NaN
16,P117,Smartphone Tripod,1199,4.3,760,210,NaN
17,P118,Laptop Backpack,1999,4.4,1600,420,NaN
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,NaN
19,P120,LED Desk Lamp,1299,4.3,980,260,NaN
20,P121,Phone Holder,499,4.0,420,150,NaN
21,P122,Wireless Keyboard,2499,4.4,1450,310,NaN
22,P123,Portable Monitor,8999,4.6,1250,170,NaN
23,P124,Smart Plug,799,4.2,720,210,NaN
24,P125,WiFi Router,3499,4.5,2100,390,NaN
25,P126,Graphics Tablet,4599,4.4,980,160,NaN
26,P127,VR Headset,12999,4.7,3100,140,NaN
27,P128,Microphone,2199,4.3,1300,270,NaN
28,P129,Smart Light Bulb,699,4.2,880,240,NaN
29,P130,Laptop Cooling Pad,1499,4.3,990,260,NaN
30,P131,Action Camera,9999,4.6,2100,200,NaN
31,P132,Smart Doorbell,5999,4.5,1750,180,NaN
32,P133,Streaming Stick,3499,4.4,2500,430,NaN
33,P134,Portable Projector,11999,4.6,1450,120,NaN
34,P135,Gaming Chair,15999,4.7,2100,90,NaN
35,P136,Desk Organizer,599,4.1,450,160,NaN
36,P137,USB Flash Drive,799,4.2,900,320,NaN
37,P138,Phone Screen Protector,299,4.0,600,380,NaN
38,P139,Laptop Sleeve,999,4.3,720,210,NaN
39,P140,Wireless Presenter,1499,4.4,520,130,NaN
40,P141,Tablet Keyboard Case,2999,4.5,850,150,NaN
41,P142,Smart Thermostat,10999,4.6,1200,110,NaN
42,P143,Security Camera,4999,4.4,2100,260,NaN
43,P144,Drone Camera,24999,4.7,1800,70,NaN
44,P145,Electric Kettle,1999,4.3,1400,310,NaN
45,P146,Air Fryer,7999,4.6,2200,200,NaN
46,P147,Robot Vacuum,18999,4.5,1650,120,NaN
47,P148,Smart Scale,2499,4.4,980,170,NaN
48,P149,Digital Photo Frame,3499,4.3,870,150,NaN
49,P150,Portable Fan,999,4.2,760,240,NaN

In [ ]:
#Z-Score Normalization for Reviews

mean_reviews = d['Reviews'].mean()
std_reviews = d['Reviews'].std()
d['Reviews_Zscore'] = (d['Reviews'] - mean_reviews) / std_reviews

d

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_Normalized,Reviews_Zscore
0,P101,Wireless Mouse,799,4.3,1520,350,2.214615,0.075943
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.797611,-0.577069
2,P103,USB Keyboard,699,4.1,870,180,1.202470,-0.710090
3,P104,Gaming Headset,2499,4.6,2100,410,0.068866,0.777327
4,P105,Smartwatch,3999,4.4,3050,520,0.311781,1.926145
5,P106,Power Bank,1199,4.2,1750,390,0.170081,0.354078
6,P107,Laptop Stand,899,4.0,620,140,NaN,-1.012411
7,P108,Webcam,1899,4.3,1120,260,NaN,-0.407770
8,P109,Portable SSD,5499,4.7,1850,330,NaN,0.475006
9,P110,Wireless Charger,999,4.2,760,190,NaN,-0.843111
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,NaN,3.316819
11,P112,Mechanical Keyboard,4599,4.5,2100,290,NaN,0.777327
12,P113,Gaming Mouse,1599,4.4,1300,340,NaN,-0.190099
13,P114,Tablet Stand,699,4.1,540,120,NaN,-1.109154
14,P115,USB Hub,899,4.2,870,200,NaN,-0.710090
15,P116,External Hard Drive,6499,4.6,2300,310,NaN,1.019183
16,P117,Smartphone Tripod,1199,4.3,760,210,NaN,-0.843111
17,P118,Laptop Backpack,1999,4.4,1600,420,NaN,0.172685
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,NaN,2.470321
19,P120,LED Desk Lamp,1299,4.3,980,260,NaN,-0.577069
20,P121,Phone Holder,499,4.0,420,150,NaN,-1.254267
21,P122,Wireless Keyboard,2499,4.4,1450,310,NaN,-0.008707
22,P123,Portable Monitor,8999,4.6,1250,170,NaN,-0.250563
23,P124,Smart Plug,799,4.2,720,210,NaN,-0.891483
24,P125,WiFi Router,3499,4.5,2100,390,NaN,0.777327
25,P126,Graphics Tablet,4599,4.4,980,160,NaN,-0.577069
26,P127,VR Headset,12999,4.7,3100,140,NaN,1.986609
27,P128,Microphone,2199,4.3,1300,270,NaN,-0.190099
28,P129,Smart Light Bulb,699,4.2,880,240,NaN,-0.697998
29,P130,Laptop Cooling Pad,1499,4.3,990,260,NaN,-0.564977
30,P131,Action Camera,9999,4.6,2100,200,NaN,0.777327
31,P132,Smart Doorbell,5999,4.5,1750,180,NaN,0.354078
32,P133,Streaming Stick,3499,4.4,2500,430,NaN,1.261039
33,P134,Portable Projector,11999,4.6,1450,120,NaN,-0.008707
34,P135,Gaming Chair,15999,4.7,2100,90,NaN,0.777327
35,P136,Desk Organizer,599,4.1,450,160,NaN,-1.217989
36,P137,USB Flash Drive,799,4.2,900,320,NaN,-0.673812
37,P138,Phone Screen Protector,299,4.0,600,380,NaN,-1.036597
38,P139,Laptop Sleeve,999,4.3,720,210,NaN,-0.891483
39,P140,Wireless Presenter,1499,4.4,520,130,NaN,-1.133339
40,P141,Tablet Keyboard Case,2999,4.5,850,150,NaN,-0.734276
41,P142,Smart Thermostat,10999,4.6,1200,110,NaN,-0.311027
42,P143,Security Camera,4999,4.4,2100,260,NaN,0.777327
43,P144,Drone Camera,24999,4.7,1800,70,NaN,0.414542
44,P145,Electric Kettle,1999,4.3,1400,310,NaN,-0.069171
45,P146,Air Fryer,7999,4.6,2200,200,NaN,0.898255
46,P147,Robot Vacuum,18999,4.5,1650,120,NaN,0.233150
47,P148,Smart Scale,2499,4.4,980,170,NaN,-0.577069
48,P149,Digital Photo Frame,3499,4.3,870,150,NaN,-0.710090
49,P150,Portable Fan,999,4.2,760,240,NaN,-0.843111

In [ ]:
#Decimal Scaling for Units Sold

max_units_sold = d['Units_Sold'].max()

d['Units_Sold_Scaled'] = d['Units_Sold'] / 1000

d

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_Normalized,Reviews_Zscore,Units_Sold_Scaled
0,P101,Wireless Mouse,799,4.3,1520,350,2.214615,0.075943,0.35
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.797611,-0.577069,0.22
2,P103,USB Keyboard,699,4.1,870,180,1.202470,-0.710090,0.18
3,P104,Gaming Headset,2499,4.6,2100,410,0.068866,0.777327,0.41
4,P105,Smartwatch,3999,4.4,3050,520,0.311781,1.926145,0.52
5,P106,Power Bank,1199,4.2,1750,390,0.170081,0.354078,0.39
6,P107,Laptop Stand,899,4.0,620,140,NaN,-1.012411,0.14
7,P108,Webcam,1899,4.3,1120,260,NaN,-0.407770,0.26
8,P109,Portable SSD,5499,4.7,1850,330,NaN,0.475006,0.33
9,P110,Wireless Charger,999,4.2,760,190,NaN,-0.843111,0.19
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,NaN,3.316819,0.61
11,P112,Mechanical Keyboard,4599,4.5,2100,290,NaN,0.777327,0.29
12,P113,Gaming Mouse,1599,4.4,1300,340,NaN,-0.190099,0.34
13,P114,Tablet Stand,699,4.1,540,120,NaN,-1.109154,0.12
14,P115,USB Hub,899,4.2,870,200,NaN,-0.710090,0.20
15,P116,External Hard Drive,6499,4.6,2300,310,NaN,1.019183,0.31
16,P117,Smartphone Tripod,1199,4.3,760,210,NaN,-0.843111,0.21
17,P118,Laptop Backpack,1999,4.4,1600,420,NaN,0.172685,0.42
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,NaN,2.470321,0.53
19,P120,LED Desk Lamp,1299,4.3,980,260,NaN,-0.577069,0.26
20,P121,Phone Holder,499,4.0,420,150,NaN,-1.254267,0.15
21,P122,Wireless Keyboard,2499,4.4,1450,310,NaN,-0.008707,0.31
22,P123,Portable Monitor,8999,4.6,1250,170,NaN,-0.250563,0.17
23,P124,Smart Plug,799,4.2,720,210,NaN,-0.891483,0.21
24,P125,WiFi Router,3499,4.5,2100,390,NaN,0.777327,0.39
25,P126,Graphics Tablet,4599,4.4,980,160,NaN,-0.577069,0.16
26,P127,VR Headset,12999,4.7,3100,140,NaN,1.986609,0.14
27,P128,Microphone,2199,4.3,1300,270,NaN,-0.190099,0.27
28,P129,Smart Light Bulb,699,4.2,880,240,NaN,-0.697998,0.24
29,P130,Laptop Cooling Pad,1499,4.3,990,260,NaN,-0.564977,0.26
30,P131,Action Camera,9999,4.6,2100,200,NaN,0.777327,0.20
31,P132,Smart Doorbell,5999,4.5,1750,180,NaN,0.354078,0.18
32,P133,Streaming Stick,3499,4.4,2500,430,NaN,1.261039,0.43
33,P134,Portable Projector,11999,4.6,1450,120,NaN,-0.008707,0.12
34,P135,Gaming Chair,15999,4.7,2100,90,NaN,0.777327,0.09
35,P136,Desk Organizer,599,4.1,450,160,NaN,-1.217989,0.16
36,P137,USB Flash Drive,799,4.2,900,320,NaN,-0.673812,0.32
37,P138,Phone Screen Protector,299,4.0,600,380,NaN,-1.036597,0.38
38,P139,Laptop Sleeve,999,4.3,720,210,NaN,-0.891483,0.21
39,P140,Wireless Presenter,1499,4.4,520,130,NaN,-1.133339,0.13
40,P141,Tablet Keyboard Case,2999,4.5,850,150,NaN,-0.734276,0.15
41,P142,Smart Thermostat,10999,4.6,1200,110,NaN,-0.311027,0.11
42,P143,Security Camera,4999,4.4,2100,260,NaN,0.777327,0.26
43,P144,Drone Camera,24999,4.7,1800,70,NaN,0.414542,0.07
44,P145,Electric Kettle,1999,4.3,1400,310,NaN,-0.069171,0.31
45,P146,Air Fryer,7999,4.6,2200,200,NaN,0.898255,0.20
46,P147,Robot Vacuum,18999,4.5,1650,120,NaN,0.233150,0.12
47,P148,Smart Scale,2499,4.4,980,170,NaN,-0.577069,0.17
48,P149,Digital Photo Frame,3499,4.3,870,150,NaN,-0.710090,0.15
49,P150,Portable Fan,999,4.2,760,240,NaN,-0.843111,0.24

In [ ]:
#Turning categorical variables into quantitative variables
#Label Encoding
df = pd.read_csv("/content/Student-Dataset.csv")

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['Gender_LabelEncoded'] = le.fit_transform(df['Gender'])
df['Department_LabelEncoded'] = le.fit_transform(df['Department'])
df['Placement_Status_LabelEncoded'] = le.fit_transform(df['Placement_Status'])

print("DataFrame with Label Encoded columns:")
df

DataFrame with Label Encoded columns:

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_LabelEncoded,Department_LabelEncoded,Placement_Status_LabelEncoded
0,101,Female,Computer,8.2,0,92,Placed,450000,0,1,1
1,102,Male,IT,7.5,1,85,Not Placed,0,1,3,0
2,103,Female,ENTC,9.1,0,96,Placed,550000,0,2,1
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,1,4,0
4,105,Female,Computer,8.7,0,88,Placed,480000,0,1,1
5,106,Male,Civil,7.2,3,72,Not Placed,0,1,0,0
6,107,Female,IT,8.9,0,91,Placed,500000,0,3,1
7,108,Male,Computer,6.5,1,80,Not Placed,0,1,1,0
8,109,Female,ENTC,7.8,0,84,Placed,420000,0,2,1
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,1,4,0

In [ ]:
df_onehot_department = pd.get_dummies(df, columns=['Department'], drop_first=True)
print("DataFrame after One-Hot Encoding for Department only:")
df_onehot_department

DataFrame after One-Hot Encoding for Department only:

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_LabelEncoded,Department_LabelEncoded,Placement_Status_LabelEncoded,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,0,1,1,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,1,3,0,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,0,2,1,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,1,4,0,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,0,1,1,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,1,0,0,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,0,3,1,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,1,1,0,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,0,2,1,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,1,4,0,False,False,False,True

In [ ]:
df_department_dummies = pd.get_dummies(df, columns=['Department'], drop_first=True)
print("DataFrame with One-Hot Encoded Department column:")
df_department_dummies

DataFrame with One-Hot Encoded Department column:

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_LabelEncoded,Department_LabelEncoded,Placement_Status_LabelEncoded,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,0,1,1,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,1,3,0,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,0,2,1,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,1,4,0,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,0,1,1,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,1,0,0,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,0,3,1,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,1,1,0,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,0,2,1,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,1,4,0,False,False,False,True